#!/bin/sh /etc/rc.common
# Copyright (C) 2017-2022 The Quick Route Authors.

START=99
USE_PROCD=1
#PROCD_DEBUG=1

quickroute="/usr/sbin/quickroute"
quickroute_pid_file="/var/run/quickroute.pid"

start_service() {
	procd_open_instance "quickroute"
	procd_set_param command "$quickroute"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile "$quickroute_pid_file"
	procd_set_param user quickroute
	procd_close_instance
}
